# Generated by Django 5.0.3 on 2025-02-14 08:26

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0001_initial"),
        ("sponsor_us", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="sponsor name")),
                (
                    "logo",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to="sponsors/"
                    ),
                ),
                (
                    "sponsor_type",
                    models.CharField(
                        choices=[
                            ("C", "Corporate Sponsor"),
                            ("S", "Special Sponsor"),
                            ("G", "Grant"),
                            ("D", "Diversity"),
                            ("I", "Individual Sponsor"),
                        ],
                        max_length=1,
                        verbose_name="sponsor type",
                    ),
                ),
                ("is_visible", models.BooleanField(default=False)),
                (
                    "website",
                    models.URLField(
                        blank=True, default="", help_text="Link to Sponsor website"
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Please enter only the user name eg.'mawy_7'",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "linkedin",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Please enter only the user name eg.'mawy_7'",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "biography",
                    markdownx.models.MarkdownxField(
                        blank=True,
                        default="",
                        help_text="Description of the Sponsor",
                        null=True,
                    ),
                ),
                (
                    "show_biography",
                    models.BooleanField(
                        default=False,
                        help_text="Untick if the company only wants their logo displayed on our website. Not all companies want their information on the site.",
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "event_year",
                    models.ForeignKey(
                        default="2024",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsors",
                        to="home.eventyear",
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sponsor_us.sponsorshiptier",
                        verbose_name="sponsorship tier",
                    ),
                ),
            ],
            options={
                "managed": True,
            },
        ),
    ]
